[mcp_servers.cloudflare]
url = "https://mcp.cloudflare.com/mcp"

[mcp_servers.playwright]
command = "npx"
args = [
    "@playwright/mcp@latest",
    "--browser",
    "chromium",
]

[mcp_servers.playwright-firefox]
command = "npx"
args = [
    "@playwright/mcp@latest",
    "--browser",
    "firefox",
]
